# Site settings
title: dario • Sécurité • Vie Privée
description: La sécurité est une exigence commerciale. La protection de la vie privée est un avantage concurrentiel. Comprendre - Agir.
author: dario.com
url: https://dario.site
english_url: https://dario.com
baseurl: ''
resources_url: 'resources'
logo: "/img/chklst.png"
email: contact@dario.site
twitter_username:
telephone_number:
copyright: dario.site • Sécurité • Vie Privée
gems:
  - jekyll-sitemap
# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]
# Build settings
markdown: kramdown
