# Bacis settings
title: dario.site • Sécurité • Vie Privée
description: La sécurité est une exigence commerciale. La protection de la vie privée est un avantage concurrentiel. Protégez vos données et votre entreprise. dario.site
author: _config.yml author
# Language format language_TERRITORY. Default is en_US
lang: fr_CA
# website logos, images & icons  check / at begining
logo: /img/chklst.png
image: /img/header.jpg
# urls
url: https://dario.site
english_url: https://dario.com
french_url: https://dario.site
baseurl: ''
resources_url: 'resources'

# copyright text in footer
copyright: dario.site • Sécurité • Vie Privée

# email address
email: contact@dario.site
email_username: contact@dario.site
# email address in privacy policy
email_privacy: privacy@dario.site

# contact telephone number
telephone_number:

# search tracking id for dario.site
google_tracking_id: UA-98131817-3

webmaster_verifications:
  google: B3IJ_LqW_yl1k4gLEYqap8F0_sHGRS_7thoEclC_3kg
  bing: AC24F3DF5CA3A5221FB7E01EF2D9AAC4
  alexa:
  yandex:
  baidu:

# Social accounts
twitter_username: darioS3C
github_username:
facebook_username:

twitter:
  username: darioS3C

facebook:
  app_id:
  publisher:
  admins:

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]

# gems
gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
