# Site settings
title: dario • Sécurité • Vie Privée
description: Comprendre - Agir. La sécurité est une exigence commerciale. La protection de la vie privée est un avantage concurrentiel.
author: dario.com
url: https://dario.site
baseurl: ''
logo: "/img/chklst.png"
email: contact@dario.com
twitter_username: darioS3C
telephone_number: +1-514-572-0424
copyright:
gems:
  - jekyll-sitemap
# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]
# Build settings
markdown: kramdown
